### ISSUE TITLE
Bug in "link text" locator

### ISSUE THREAD

**Issue by jefleponot** [SeleniumBuilder/se-builder#224]
Hi,

Your idea of "link text" locator is great. This selector misses a lot in css3 selector.
But it don't work sometimes because of your function "removeHTMLTags" in the "locator.js" file.

I found a simple code to resolve the trouble of regular expressions -> we just need th "document.createTreeWalker" function :-)

here is another function to replace "removeHTMLTags"

    function textNodesUnder(el){
        var n, str='', walk=document.createTreeWalker(el,NodeFilter.SHOW_TEXT,null,false);
        while(n=walk.nextNode()) str=str.concat(n.nodeValue);
        str = str.replace(/&(lt|gt|nbsp);/g, function (strMatch, p1) {
            return (p1 === "lt") ? "<" : ((p1 === "gt") ? ">" : " ");
        });
        return str.replace(/\s+/g," ").trim();
    }

**Comment by Zarkonnen** [comment]
Closing as "working as expected".
