### ISSUE TITLE
Selenese "select" with optionLocator incorrect converted

### ISSUE THREAD

**Issue by dirkluijk** [SeleniumBuilder/se-builder#239]
Hi,

The Selenium 1 command
```java
selenium.select("id=my_list", "label=Some text");
```
is incorrectly converted to the WebDriver command
```java
wd.findElement(By.xpath("//*[@id='my_list']/*[. = 'label=Some text']")).click();
```
It should be:
```java
wd.findElement(By.xpath("//*[@id='my_list']/*[text() = 'Some text']")).click();
```

Is this a bug or can I prevent this by using a different Selenium 1 command? I currently have a lot of Selenium 1 testscripts which must be converted to Selenium 2, and I want to use the Selenium Builder for it.

**Comment by Zarkonnen** [comment]
Right, I've been working on improving this. Conversion now does the following things:

* `my_list` `label=Some text` becomes `xpath: //*[@id='my_list']/*[. = 'Some text']`
* `my_list` `id=someid` becomes `id: someid`
* `my_list` `value=myvalue` becomes `xpath: //*[@id='my_list']/*[@value = 'myvalue']`
* `my_list` `index=3` becomes `xpath: //*[@id='my_list']/*[4]`

(The index is adjusted to account for xpath's 1-based indexing.)

Looks good?
