### ISSUE TITLE
Define Screen resolution when running tests

### ISSUE THREAD

**Issue by dstoica1** [SeleniumBuilder/se-builder#251]
Is it possible to somehow define a screen resolution when running tests?

I have a test that works fine when I run the test through the desktop browser via the extension.

However I'm trying to automate things and when I run the test via the Selenium Builder Jenkins plugin it fails.

I took a screenshot in the test and it turns out the screen is very small which triggers my responsive design and the menu item I was looking for isn't displayed.

**Comment by davidlinse** [comment]
Afaik there is already an implementation to set the window-size but it's not available as a single step for some reasons. @Zarkonnen .. ?
e.g.
```js
...
// components/command_processor.js:66666
FirefoxDriver.prototype.getWindowSize ..
FirefoxDriver.prototype.setWindowSize ..
...
```
~david

**Comment by dstoica1** [comment]
Thanks David, do you know if there are any plans to implement this enhancement?

**Comment by Zarkonnen** [comment]
Looks like there *is* a JSON wire protocol equivalent, so it should be possible. I'll see that I can put it in.

**Comment by dstoica1** [comment]
That's great, thank you.
