### ISSUE TITLE
verifyEval is broken

### ISSUE THREAD

**Issue by Zarkonnen** [SeleniumBuilder/se-builder#258]
## Reproduce
Run the following script in local playback:

    {
      "type": "script",
      "seleniumVersion": "2",
      "formatVersion": 2,
      "steps": [
        {
          "type": "get",
          "url": "http://www.metafilter.com/"
        },
        {
          "type": "verifyEval",
          "script": "return 1 + 1",
          "value": "2"
        }
      ],
      "data": {
        "configs": {},
        "source": "none"
      },
      "inputs": [],
      "timeoutSeconds": 60
    }

## Expected
The verifyEval step should pass.

## Observed
The step fails with a "Script evaluation failed message."

Note that this runs correctly on remote playback.

**Comment by Ahisandra** [comment]
The same for storeEval. Example from github doesn't work
{
  "type": "script",
  "seleniumVersion": "2",
  "formatVersion": 2,
  "steps": [
    {
      "type": "get",
      "url": "http://saucelabs.com/test/guinea-pig"
    },
    {
      "type": "verifyElementPresent",
      "locator": {
        "type": "css selector",
        "value": "#i_am_an_id"
      }
    },
    {
      "type": "storeEval",
      "script": "return document.querySelectorAll('body div').length",
      "variable": "num_of_div_elements"
    },
    {
      "type": "verifyEval",
      "script": "return ${num_of_div_elements}",
      "value": "7"
    },
    {
      "type": "verifyEval",
      "script": "return document.querySelectorAll('body div').length >= 7",
      "value": "true"
    }
  ],
  "data": {
    "configs": {},
    "source": "none"
  },
  "inputs": []
}

**Comment by Zarkonnen** [comment]
Yeah, *eval is broken. Top priority for fixing in 2.4, of course.

**Comment by Zarkonnen** [comment]
Working on this and making some progress. It appears that webdriver's `evaluate.js` is running afoul of some new security restrictions or has broken in some other way.

**Comment by gagezheng** [comment]
is the fix included in V2.3.3?

**Comment by Ahisandra** [comment]
No. Bug will be fixed in v.2.4
