### ISSUE TITLE
can't open or save se-builder scripts with FF version 38.0

### ISSUE THREAD

**Issue by russmadeira** [SeleniumBuilder/se-builder#260]
With FireFox 38.0, saving se-builder scripts results in an error:

![2](https://cloud.githubusercontent.com/assets/12448515/7637088/33ec88f6-fa20-11e4-82d5-2020da60e83d.png)

There's also an unnecessary scroll bar in the UI:

![5-14-2015 8-57-23 am](https://cloud.githubusercontent.com/assets/12448515/7637101/5129d54a-fa20-11e4-98a9-2b9f9a2ef6ae.png)

**Comment by douglashanna** [comment]
I am also having this problem with Firefox 38.0.1.

**Comment by Zarkonnen** [comment]
Noted, will look into this ASAP.

- David

**Comment by Zarkonnen** [comment]
Should be fixed now in 2.3.3.
