### ISSUE TITLE
'Script evaluation failed.' for V2.3.1

### ISSUE THREAD

**Issue by gagezheng** [SeleniumBuilder/se-builder#264]
Hi,

I use storeEval to record some data and it worked fine with V2.2.X. But after I back from vacation, 2.2 doesnt work with Firefox V37. Then i updated SeleniumBuiler to 2.3.1. Now it couldnt pass any eval as all eval reply as 'Script evaluation failed'.

How can i fix this issue?

Regards.
JJ

**Comment by Zarkonnen** [comment]
I'm just looking into this problem now, actually. :)

**Comment by Zarkonnen** [comment]
NB this is a duplicate of #258 so further stuff will happen there.
