### ISSUE TITLE
Can't Save or Export: Preferences.getString is not a function

### ISSUE THREAD

**Issue by jfeldstein** [SeleniumBuilder/se-builder#284]
<img width="662" alt="screen shot 2015-10-21 at 7 20 43 pm" src="https://cloud.githubusercontent.com/assets/172683/10655377/ed8913f2-7828-11e5-8ce2-c06ed70b23d1.png">

I also can't seem to get storeEval to work. I tried the [recommended value](https://github.com/SeleniumBuilder/se-builder/issues/109#issuecomment-31858237), returning a string... everything fails.

**Comment by ianlintner-wf** [comment]
+1

**Comment by arko19** [comment]
Same problem here on Windows 10, Firefox 42.0

**Comment by Zarkonnen** [comment]
I am fairly certain that this is a bug with an older version of Builder. Are you using the latest release from http://seleniumbuilder.github.io/se-builder/ ? The one at https://saucelabs.com/builder appears to be several minor versions out of date. :(

**Comment by arko19** [comment]
I am using the one at saucelabs.com, tomorrow I will try the one at
seleniumbuilder.github.io

**Comment by killlinuxkill** [comment]
Zarkonnen. Not work anyway. Windows 7 x 64/ Ubuntu 15.04 x 64. FF 42. And not saved and not opens script files selenium1. Look this video http://screencast.com/t/79mbbIyuJ8D

**Comment by Zarkonnen** [comment]
I am pretty certain that your screencast is not of the latest version of Builder, as it has a scroll bar display bug that got fixed by v2.3.5. Can you download the one at http://seleniumbuilder.github.io/se-builder/selenium-builder-latest.xpi and make sure the version says 2.3.5?

**Comment by killlinuxkill** [comment]
Yes. In builder v2.3.5, works export and import, as for selenium 1 and for selenium 2. Thanks for your work.

**Comment by danielsamuels** [comment]
Just to clarify, are SauceLabs and this project two different things, or are they the same?

**Comment by Zarkonnen** [comment]
[Sauce Labs](http://saucelabs.com) are the company who have been financially supporting the development of Builder. Builder is an open-source project of which I am the maintainer.
