### ISSUE TITLE
Failure to record field input (Number type)

### ISSUE THREAD

**Issue by gang126** [SeleniumBuilder/se-builder#285]
Reproduce:

Start recording at any html contains number type input field.
"
<!DOCTYPE HTML>
<html>
<body>
<form action="" method="get">
<input type="number" name="points" min="0" max="10" step="3" value="" />
<input type="submit" />
</form>
</body>
</html>
"
Click input field
Type 9

Expected:
Number 9 should be recorded.

Observed:
Number 9 is not recorded.

{
  "type": "script",
  "seleniumVersion": "2",
  "formatVersion": 2,
  "steps": [
    {
      "type": "get",
      "url": "file:///C:/Documents%20and%20Settings/Administrator/%E6%A1%8C%E9%9D%A2/%E6%96%B0%E5%BB%BA%20%E6%96%87%E6%9C%AC%E6%96%87%E6%A1%A3.html?points=//////"
    },
    {
      "type": "setElementText",
      "locator": {
        "type": "name",
        "value": "points"
      },
      "text": "9"
    }
  ],
  "data": {
    "configs": {},
    "source": "none"
  },
  "inputs": [],
  "timeoutSeconds": 60
}

I refer to issue #156 and  set the ["value": "input[type=\"number\"]", it still doesn't work.

**Comment by jkowalczyk** [comment]
+1

**Comment by Zarkonnen** [comment]
[Ported to v3](https://github.com/SeleniumBuilder/selenium-builder/issues/12)
