### ISSUE TITLE
se-builder app never launches

### ISSUE THREAD

**Issue by dotIN** [SeleniumBuilder/se-builder#288]
Env
FireFox42 & 38 (tried on both)
OS X Yesomite

When ever I try to launch se-builder , the screen hangs at iginition.js , below is the screen shot.

![screen shot 2015-12-02 at 3 17 27 pm](https://cloud.githubusercontent.com/assets/164935/11520416/1b4a4c70-9908-11e5-803e-d181d71fa485.png)

**Comment by Zarkonnen** [comment]
This should be fixed now in v3.0.5.

**Comment by dotIN** [comment]
I guess I found the issue, I installed SE Builder from Mozilaa Add-Ons that seems to not work, I realized & installed the one from http://seleniumbuilder.github.io/se-builder/ & It works fine now, Thanks for the help.
