### ISSUE TITLE
Plugin not working with Firefox 43.0.3

### ISSUE THREAD

**Issue by avernon2** [SeleniumBuilder/se-builder#289]
![2015-12-29 11_32_09-add-ons manager](https://cloud.githubusercontent.com/assets/14982179/12038729/16029574-ae20-11e5-95bb-eb8f9a5cb070.png)

Selenium Builder 2.3.5 (Disabled)  because it could not be verified for use in Firefox.

**Comment by NozomiIto** [comment]
You can download Selenium Builder 3.0.5 from https://addons.mozilla.org/ja/firefox/addon/selenium-builder , and it works well.

I don't know whether this file is official one.

**Comment by stanjer** [comment]
https://github.com/SeleniumBuilder/selenium-builder

**Comment by Zarkonnen** [comment]
Exactly! Builder v2 is at this point in basic maintenance mode, and only meant for cases where you really want to run Selenium 1 on an old Firefox version.

Future work will be on v3, with local playback coming up next.
