### ISSUE TITLE
UI doesn't always place hamburger menu pop-up in view

### ISSUE THREAD

**Issue by orcpac7** [SeleniumBuilder/se-builder#291]
Using Firefox 43.0.4, running Selenium Builder, if I click the Hamburger menu, (intending to delete a step) the popup appears to be cut off at the top, such that I can't reach the delete menu choice. (See attached screenshot).
I have tried enlarging and reducing the window magnification (CTRL-+, CTRL-minus) but I always get the same relative positioning as shown.
Would like the popup to detect it's position relative to top of window and if negative, slide down to be within viewport...
![hamburgermenu](https://cloud.githubusercontent.com/assets/1434423/12492801/06994ef6-c050-11e5-933f-372c36d111e3.PNG)

**Comment by orcpac7** [comment]
Unable to reproduce today. Lets mark this one as done or overcome by events.

**Comment by Zarkonnen** [comment]
[Ported to here.](https://github.com/SeleniumBuilder/selenium-builder/issues/9)

**Comment by Zarkonnen** [comment]
(And I was able to repro it in v3.0.6, so it looks like it's baaaack)
