### ISSUE TITLE
How to get text and verify 

### ISSUE THREAD

**Issue by gowthaminaidu** [SeleniumBuilder/se-builder#293]
If i have to get text of any element and verify that text is visible or not in some other page, I could not do it in builder. How this kind of validations are done using Builder.
eg:
element.getAttribute()
element.getText()

Thank you,
Gowthami.

**Comment by Zarkonnen** [comment]
You can use storeElementText / storeElementAttribute. Here is an example 
script that goes to metafilter.com, stores the title of the first entry, 
then goes into the comments for that entry, and checks that the stored 
title is present on the page:

{
   "type": "script",
   "seleniumVersion": "2",
   "formatVersion": 2,
   "steps": [
     {
       "type": "get",
       "url": "http://www.metafilter.com/"
     },
     {
       "type": "storeText",
       "locator": {
         "type": "xpath",
         "value": "//div[@id='posts']/h2[2]/a"
       },
       "variable": "postText"
     },
     {
       "type": "clickElement",
       "locator": {
         "type": "css selector",
         "value": "a.more"
       }
     },
     {
       "type": "verifyTextPresent",
       "text": "${postText}"
     }
   ],
   "data": {
     "configs": {},
     "source": "none"
   },
   "inputs": [],
   "timeoutSeconds": 60
}

Hope that's helpful. :)

- David
