### ISSUE TITLE
how to run a selenium builder test using selenium server

### ISSUE THREAD

**Issue by moatazselim** [SeleniumBuilder/se-builder#296]

**Comment by Zarkonnen** [comment]
* Run it from Builder using the "Run on Selenium Server" command in the Run menu.
* Export it to one of the language bindings.
* Save it as JSON and run it using [Java SeInterpreter](https://github.com/SeleniumBuilder/se-builder/wiki/Se-Interpreter)
* Save it as JSON and run it using [node se-interpreter](https://www.npmjs.com/package/se-interpreter)
